### ISSUE TITLE
How could I add a new device?

### ISSUE THREAD

**Issue by flier268** [spiliot/USBHid#1]
I have try to set myHidDevice=null  and then let it be new one
but,after 5 times,I got a wrong , safehandle is close.

**Comment by flier268** [comment]
System.ObjectDisposedException: 'Safe handle has been closed'
![image](https://user-images.githubusercontent.com/19989232/38004953-33dd5d4a-3271-11e8-9207-45dbe22d0901.png)

**Comment by spiliot** [comment]
I'm sorry for taking so long to notice this issue, I apparently missed the notification. Unfortunately I'm not sure what exactly you're trying to achieve and what steps you take, you need to be more specific and maybe provide a minimal code example.

**Comment by flier268** [comment]
I try to let it support connect to new device,three month ago.
I set myHidDevice=null to reset it,but it fail,it is not a right way,because I did not do UnregisterDeviceNotification.
After  two week,I got it,it can add a new device now.
It also support win7 now(because win7's report length not equal win8 later,so it have some error in your project under win7)

Congratulations!!
(≧▽≦)

**Comment by spiliot** [comment]
I'm glad you managed to find a way! Since there doesn't seem to be a problem anymore I'll close this issue now.
